version: '3.8'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: